alter session set "_ORACLE_SCRIPT"=true; 
 
CREATE USER SPENDING_MANAGER IDENTIFIED BY SPENDING_MANAGER; 
 
GRANT CONNECT TO SPENDING_MANAGER; 
 
GRANT CONNECT, RESOURCE, DBA TO SPENDING_MANAGER; 
 
GRANT UNLIMITED TABLESPACE TO SPENDING_MANAGER; 
 
grant all privileges to SPENDING_MANAGER; 

commit;