-- TABLE SPENTS
CREATE TABLE SPENTS ( 
  ID INTEGER NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(100) NOT NULL,
  DATE_SPENT DATE,
  AMOUNT NUMBER(10,2),
  CREATED_DATE TIMESTAMP WITH TIME ZONE,
  LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
); 

-- CONSTRAINT SPENTS
ALTER TABLE SPENTS ADD CONSTRAINT SPENTS_ID_PK PRIMARY KEY (ID) ENABLE;

-- SEQUENCE SPENTS
CREATE SEQUENCE SPENTS_ID_SEQ START WITH 1;


-- TABLE TAGS
CREATE TABLE TAGS ( 
  ID INTEGER NOT NULL,  
  SPENT_ID INTEGER,
  NAME VARCHAR2(50) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE,
  LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
); 

-- CONSTRAINT TAGS
ALTER TABLE TAGS ADD CONSTRAINT TAGS_ID_PK PRIMARY KEY (ID) ENABLE;

-- INDEX TAGS
CREATE SEQUENCE TAGS_ID_SEQ START WITH 1;

-- FOREIGN KEY TAGS
ALTER TABLE TAGS ADD CONSTRAINT TAGS_ID_FK FOREIGN KEY (SPENT_ID) REFERENCES SPENTS(ID);